name: Release

on:
    # Khuyến nghị theo tag để mỗi version ra một Release riêng
    push:
        tags:
            - "v*.*.*"
    # Nếu bạn muốn cứ push main là build thì dùng:
    # push:
    #   branches: [ main ]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install deps
              run: |
                  npm ci
                  npm run postinstall --if-present

            - name: Build (webpack -> release/app/dist)
              env:
                  NODE_ENV: production
              run: npm run build

            - name: Build & Publish macOS (unsigned)
              env:
                  # Token để upload asset sang Repo B (public)
                  GH_TOKEN: ${{ secrets.RELEASES_REPO_TOKEN }}
              run: |
                  # Nếu template ERB có afterSign/notarize, build unsigned bằng identity=null
                  npx electron-builder --mac --publish always --config.mac.identity=null

    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install deps
              run: |
                  npm ci
                  npm run postinstall --if-present

            - name: Build (webpack -> release/app/dist)
              env:
                  NODE_ENV: production
              run: npm run build

            - name: Build & Publish Windows (unsigned)
              env:
                  GH_TOKEN: ${{ secrets.RELEASES_REPO_TOKEN }}
              run: |
                  npx electron-builder --win nsis --publish always
